# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

#orbs:
#  node: circleci/node@4.7

#dependencies:
#  pre:
#    - npm install npm@latest -g # Should fix bug in ng test
#    - npm install angular-cli@latest -g

jobs:
  build-and-test:
    working_directory: ~/anman
    docker:
      - image: circleci/node:16.6-browsers
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      # Lint the source code
      - run:
          name: Linting
          command: npm run lint
      # Test the source code
      - run:
          name: Testing
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      # End to End test
 #     - run:
 #         name: End to End Test
 #         command: npm run e2e --
#          command: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Build docker image for manager-frontend
          command: docker build -t jukusoft/anman-manager-frontend:${CIRCLE_BRANCH}-latest -f Dockerfile .
      - run:
          name: Docker login
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push docker image for manager-frontend
          command: docker push jukusoft/anman-manager-frontend:${CIRCLE_BRANCH}-latest


workflows:
  test_my_app:
    jobs:
      - build-and-test
