# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '15.1'
    steps:
      - checkout
      - node/install-packages
      - run:
        command: ng test --watch false --single-run
#          command: npm run test --watch false --single-run

#      - setup_remote_docker:
#          version: 20.10.6
#      - run:
#          name: Build docker image for manager-frontend
#          command: docker build -t jukusoft/anman-manager-frontend:${CIRCLE_BRANCH}-latest -f Dockerfile .
#      - run:
#          name: Docker login
#          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#      - run:
#          name: Push docker image for manager-frontend
#          command: docker push jukusoft/anman-manager-frontend:${CIRCLE_BRANCH}-latest


workflows:
  test_my_app:
    jobs:
      - build-and-test
