# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

workflows:
  sample:
    jobs:
      - node/test:
          version: '15.1'
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Build docker image for manager-frontend
          command: docker build -t jukusoft/anman-manager-frontend:${CIRCLE_BRANCH}-latest -f Dockerfile .
      - run:
          name: Docker login
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push docker image for manager-frontend
          command: docker push jukusoft/anman-manager-frontend:${CIRCLE_BRANCH}-latest

